### ISSUE TITLE
可以用在C++程序的Unit test吗？

### ISSUE THREAD

**Issue by lclfans** [ZJU-ACES-ISE/ChatUniTest#1]
不行的话，要做哪些工作来支持C++程序的Unit test？

**Comment by xiezhuokui** [comment]
你好，感谢你关注我们的工作。我们目前只支持对java程序的单元测试生成。如果你希望在C++上进行测试生成，需要修改的地方有：
  1. Parser: 需要将支持java的parser调整为支持C++的Parser
  2. 需要调整 rule-based 修复规则：当前我们的工作只能针对受损的java代码进行修复
  3. 需要调整运行测试的命令：使得C++的测试能够编译并运行

如果你还有疑问，欢迎继续讨论

祝好，
ZJU ISE 团队成员
