### ISSUE TITLE
哪里获取java-grammar.so 和C++的grammar

### ISSUE THREAD

**Issue by lclfans** [ZJU-ACES-ISE/ChatUniTest#2]
hi Expert，
     看到代码里在使用tree-sitter时，需要一个java-grammar.so 文件，我想问一下，这个文件是怎么得到？
如果我们需要支持C/C++ code的话，怎么获取这个grammar 动态库文件呢？

**Comment by xiezhuokui** [comment]
你好：
       java-grammar.so 文件可以在 https://github.com/microsoft/methods2test/blob/main/scripts/java-grammar.so 找到并下载，我们目前尚未研究针对 C++ 程序的单元测试自动生成，不过你可以尝试使用 Clang 来进行解析。
       Ubuntu:
       `sudo apt-get install clang python3-clang`
      然后使用命令:
      `find /usr -name libclang.so`
      来找到该动态库文件。

祝好，
ZJU ISE 团队成员

**Comment by lclfans** [comment]
OK, thanks. 
另一个问题：
我看tree-sitter有多个相关项目， 分别对不同的编程语言提供了grammar，这些能与chatUnitTest配合使用吗？
Java grammar for tree-sitter
https://github.com/tree-sitter/tree-sitter-java
C++ grammar for tree-sitter
https://github.com/tree-sitter/tree-sitter-cpp
C grammar for tree-sitter
https://github.com/tree-sitter/tree-sitter-c

**Comment by xiezhuokui** [comment]
不支持与 ChatUniTest 配合使用，因为 ChatUniTest 的单元测试提取、代码修复、以及运行和编译都是针对 java 程序设计和开发。因此，如果你希望针对 C/C++ 程序生成单元测试的话，需要修改的地方非常多，建议可以参考本工具另外进行开发。

**Comment by xiezhuokui** [comment]
不支持与 ChatUniTest 配合使用，因为 ChatUniTest 的单元测试提取、代码修复、以及运行和编译都是针对 java 程序设计和开发。因此，如果你希望针对 C/C++ 程序生成单元测试的话，需要修改的地方非常多，建议可以参考本工具另外进行开发。
