### ISSUE TITLE
复现需要的数据和测试脚本可以提供吗？

### ISSUE THREAD

**Issue by mylcode** [ZJU-ACES-ISE/ChatUniTest#4]

**Comment by coder-chenzhi** [comment]
@EarthXP 您好，感谢关注。我们目前已经没有在更新Python版本的ChatUniTest了，建议使用我们的maven插件和IDEA插件，效果会好很多。如果只是要复现原始论文，数据和测试脚本看下还能不能找到@xiezhuokui

**Comment by mylcode** [comment]
> @EarthXP 您好，感谢关注。我们目前已经没有在更新Python版本的ChatUniTest了，建议使用我们的maven插件和IDEA插件，效果会好很多。如果只是要复现原始论文，数据和测试脚本看下还能不能找到@xiezhuokui

谢谢，希望能和论文中的方法在相同条件下对比。

maven/IDEA plugins有在Defects4J上的评价和测试指标吗？

**Comment by mylcode** [comment]
![image](https://github.com/ZJU-ACES-ISE/ChatUniTest/assets/15072042/5ed769f3-e614-45dc-a039-4856a344ce0b)
scripts目录下面有几个脚本，应该和数据集构建和评测有关系，只是没有说明。能不能给一些评价用的数据集构建和跑评测结果的说明到readme？

**Comment by pilihualabi** [comment]
> ![image](https://github.com/ZJU-ACES-ISE/ChatUniTest/assets/15072042/5ed769f3-e614-45dc-a039-4856a344ce0b) scripts目录下面有几个脚本，应该和数据集构建和评测有关系，只是没有说明。能不能给一些评价用的数据集构建和跑评测结果的说明到readme？

请问这个目录和脚本在哪里呀？
